/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}", "./public/index.html"],
  theme: {
    container: { center: true, padding: "1rem" },
    extend: {
      fontFamily: {
        sans: ["Arial", "Helvetica", "sans-serif"],
        display: ["Arial", "Helvetica", "sans-serif"],
        mono: ["Arial", "Helvetica", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        subtle: "hsl(var(--subtle) / 0.85)",
        brand: "hsl(var(--brand))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))", soft: "hsl(var(--primary-soft))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        card: { DEFAULT: "hsl(var(--card) / 0.97)", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        success: { DEFAULT: "hsl(var(--success))", foreground: "hsl(var(--success-foreground))", soft: "hsl(var(--success-soft))" },
        warning: { DEFAULT: "hsl(var(--warning))", foreground: "hsl(var(--warning-foreground))", soft: "hsl(var(--warning-soft))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))", soft: "hsl(var(--destructive-soft))" },
      },
      borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)", xl: "calc(var(--radius) + 4px)" },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.04)",
        soft: "0 1px 2px rgb(0 0 0 / 0.04), 0 4px 16px -4px rgb(0 0 0 / 0.08)",
        pop: "0 8px 30px -8px rgb(0 0 0 / 0.25), 0 2px 6px rgb(0 0 0 / 0.06)",
      },
      keyframes: {
        "fade-in": { from: { opacity: 0 }, to: { opacity: 1 } },
        "fade-up": { from: { opacity: 0, transform: "translateY(6px)" }, to: { opacity: 1, transform: "none" } },
        "scale-in": { from: { opacity: 0, transform: "scale(.97) translateY(4px)" }, to: { opacity: 1, transform: "none" } },
        "slide-up": { from: { transform: "translateY(100%)" }, to: { transform: "none" } },
        "toast-in": { from: { opacity: 0, transform: "translateY(8px) scale(.98)" }, to: { opacity: 1, transform: "none" } },
        pop: { "0%": { transform: "scale(1)" }, "40%": { transform: "scale(1.04)" }, "100%": { transform: "scale(1)" } },
        shake: { "0%,100%": { transform: "translateX(0)" }, "25%": { transform: "translateX(-3px)" }, "75%": { transform: "translateX(3px)" } },
        shimmer: { from: { backgroundPosition: "200% 0" }, to: { backgroundPosition: "-200% 0" } },
        boop: { "0%": { transform: "scale(1)" }, "30%": { transform: "scale(0.9) translateY(1px)" }, "60%": { transform: "scale(1.12) translateY(-2px)" }, "100%": { transform: "scale(1)" } },
        hop: { "0%,100%": { transform: "translateY(0)" }, "40%": { transform: "translateY(-6px)" }, "70%": { transform: "translateY(1px)" } },
        twinkle: { "0%,100%": { opacity: "0.25" }, "50%": { opacity: "0.9" } },
        flash: { "0%,40%": { backgroundColor: "hsl(var(--accent))" }, "100%": { backgroundColor: "transparent" } },
        press: { "0%": { transform: "scale(1)" }, "35%": { transform: "scale(0.96)" }, "70%": { transform: "scale(1.015)" }, "100%": { transform: "scale(1)" } },
        "correct-glow": { "0%": { boxShadow: "0 0 0 0 hsl(var(--success) / 0.45)" }, "60%": { boxShadow: "0 0 0 7px hsl(var(--success) / 0.12)" }, "100%": { boxShadow: "0 0 0 10px hsl(var(--success) / 0)" } },
        "tick-pop": { "0%": { transform: "scale(0.3) rotate(-20deg)", opacity: "0" }, "55%": { transform: "scale(1.25) rotate(4deg)", opacity: "1" }, "100%": { transform: "scale(1) rotate(0)" } },
        flicker: { "0%,100%": { transform: "scale(1) rotate(-2deg)" }, "50%": { transform: "scale(1.08) rotate(2deg)" } },
      },
      animation: {
        "fade-in": "fade-in .2s ease-out both",
        "fade-up": "fade-up .28s cubic-bezier(.2,.8,.2,1) both",
        "scale-in": "scale-in .18s cubic-bezier(.2,.8,.2,1) both",
        "slide-up": "slide-up .26s cubic-bezier(.2,.8,.2,1) both",
        "toast-in": "toast-in .22s cubic-bezier(.2,.8,.2,1) both",
        pop: "pop .3s ease-out",
        shake: "shake .25s ease-in-out 2",
        shimmer: "shimmer 1.6s linear infinite",
        boop: "boop .38s cubic-bezier(.3,.7,.4,1.4)",
        hop: "hop .45s cubic-bezier(.3,.7,.4,1.4)",
        twinkle: "twinkle 4s ease-in-out infinite",
        flash: "flash 2s ease-out",
        press: "press .32s cubic-bezier(.3,.7,.4,1.3)",
        "correct-glow": "correct-glow .7s ease-out both",
        "tick-pop": "tick-pop .42s cubic-bezier(.3,.7,.4,1.4) both",
        flicker: "flicker 1.6s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
